version: "3.9"


services:
  db:
    image: crzysan/mssql-docker:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_DB: mydb
      MSSQL_USER: myuser
      MSSQL_PASSWORD: Mypass1
    ports:
      - "1433:1433"
    container_name: mssql-server

  myapp:
    build: .
    environment:
      SECRET_KEY: ${{ MY_SECRET_KEY }}
      DATABASE_NAME: mydb
      DATABASE_HOST: db
      DATABASE_PASS: Passw0rd
      DATABASE_USER: SA
      DATABASE_PORT: 1433
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: myapp-web
