version: "3.9"


services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_DB: mydb
      MSSQL_USER: myuser
      MSSQL_PASSWORD: Mypass123
    ports:
      - "1433:1433"
    volumes:
      - ./.mssqlscripts:/var/opt/mssql/share:rw
    container_name: mssql-server
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash /var/opt/mssql/share/mssql_healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 240s


  myapp:
    build: .
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_NAME: mydb
      DATABASE_HOST: mssql-server
      DATABASE_PASS: Mypass123
      DATABASE_USER: myuser
      DATABASE_PORT: 1433
      DEBUG: "true"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_KEY: "${AUTH0_KEY}"
      AUTH0_SECRET: "${AUTH0_SECRET}"
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: myapp-web
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:8000 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 240s

