version: "3.9"


services:
  db:
    image: crzysan:mssql-docker:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_DB: mydb
      MSSQL_USER: myuser
      MSSQL_PASSWORD: Mypass1
    ports:
      - "1433:1433"
    container_name: mssql-server
  webapp:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
