version: "3.9"


services:
  myapp:
    build: .
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_NAME: mydb
      DATABASE_HOST: mssql-server
      DATABASE_PASS: Mypass123
      DATABASE_USER: myuser
      DATABASE_PORT: 1433
      DEBUG: "true"
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_KEY: "${AUTH0_KEY}"
      AUTH0_SECRET: "${AUTH0_SECRET}"
    ports:
      - "8000:8000"
    container_name: myapp-web
