version: "3.9"


services:
  db:
    image: crzysan/mssql-docker:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_DB: mydb
      MSSQL_USER: myuser
      MSSQL_PASSWORD: Mypass123
    ports:
      - "1433:1433"
    container_name: mssql-server

  myapp:
    build: .
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_NAME: mydb
      DATABASE_HOST: mssql-server
      DATABASE_PASS: Mypass123
      DATABASE_USER: myuser
      DATABASE_PORT: 1433
      DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: myapp-web
