---
apiVersion: v1
kind: Namespace
metadata:
  name: playground


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydb-config
  namespace: playground
data:
  ACCEPT_EULA: "Y"
  MSSQL_DB: mydb
  MSSQL_USER: myuser

---
apiVersion: v1
kind: Secret
metadata:
  name: mydb-secret
  namespace: playground
type: Opaque
data:
  SA_PASSWORD: UGFzc3cwcmQ=
  MSSQL_PASSWORD: TXlwYXNzMTIz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: playground
  labels:
    app: mydb
    type: db
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mydb
        type: db
  template:
    metadata:
      labels:
        app: mydb
        type: db
    spec:
      containers:
      - name: mydb-web
        image: crzysan/mssql-docker:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mydb-config
        - secretRef:
            name: mydb-secret
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
  namespace: playground
  labels:
    app: mydb
spec:
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    app: mydb
    type: db

