# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-web
  labels:
    app: myapp
    type: web
spec:
  replicas: 2
  selector:
      matchLabels:
        app: myapp
        type: web
  template:
    metadata:
      labels:
        app: myapp
        type: web
    spec:
      containers:
      - name: myapp-web
        image: crzysan/myapp:latest
        imagePullPolicy: Always
#        envFrom:
#        - configMapRef:
#            name: myapp-config
        ports:
        - containerPort: 8000

