---
apiVersion: v1
kind: Namespace
metadata:
  name: playground

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: playground
data:
  DATABASE_HOST: "mydb-svc"
  DATABASE_NAME: "mydb"
  DATABASE_USER: "myuser"
  DATABASE_PORT: "1433"
  DEBUG: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: playground
type: Opaque
data:
  SECRET_KEY: aF56MTMkcXJfc193ZDY1QGduajdhPXhzN3QwNSR3N3E4IXhfOHpzbGQj
  DATABASE_PASS: TXlwYXNzMTIz
  AUTH0_DOMAIN: ZGV2LTl4ZmRsZndzLnVzLmF1dGgwLmNvbQ==
  AUTH0_KEY: Tno0NENWaU5iMkRDT0YzcTVjb1hacmVnSVdVOVR1Vnc=
  AUTH0_SECRET: YTZXdklFdHhZVTNyQlFpYjVCRFVyTmFXZ29Cd1NtS3Q5TGxLdDhNWWIyNUlyNnNEVDJLT3ZyUHR4dDVjQ3kwTg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: playground
  labels:
    app: myapp
    type: web
spec:
  replicas: 2
  selector:
      matchLabels:
        app: myapp
        type: web
  template:
    metadata:
      labels:
        app: myapp
        type: web
    spec:
      containers:
      - name: myapp-web
        image: crzysan/myapp:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: myapp-config
        - secretRef:
            name: myapp-secret
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: playground
  labels:
    app: myapp
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
  selector:
    app: myapp
    type: web
  type: NodePort

