# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
  selector:
    app: myapp
    type: web
  type: NodePort
