# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ staging ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Label build
  build:
    runs-on: ubuntu-latest
    #env:
    #  PG_PASS: ${{ secrets.PG_PASS }}
    #  DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@postgres/postgres
    #  DJANGO_SETTINGS_MODULE: app_name.settings.dev
    #  SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #  PORT: 8000

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs myapp
    - name: Run test suite
      run: docker exec myapp pytest --skip-auth
