# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    
jobs:
  # Allows you to run this workflow manually from the Actions tab
  deploy_to_k8s_dev:
    name: Deploy to dev cluster
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script:  |
           /usr/local/bin/kubectl cluster-info --context kind-dev
           /usr/local/bin/kubectl get pod
