# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ staging ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syntaxt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        export PYTHONPATH="${PYTHONPATH}:$PWD"  # to use absolute from for import modules
        pylint --disable=F0001,C0114,C0115,C0116,E1101,R0903 feed*/*.py

  # Label build
  build:
    runs-on: ubuntu-latest
    needs: syntaxt-check 
    env:
       SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #env:
    #  PG_PASS: ${{ secrets.PG_PASS }}
    #  DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@postgres/postgres
    #  DJANGO_SETTINGS_MODULE: app_name.settings.dev
    #  SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #  PORT: 8000

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs myapp-web
    - name: Wait 30 sec untill application started
      run: wait 30
    - name: Run test
      run: curl -I localhost:8000
